config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/merchants', to: 'merchants#index'
  get '/merchants/new', to: 'merchants#new'
  get '/merchants/:id/edit', to: 'merchants#edit'
  patch '/merchants/:id', to: 'merchants#update'
  get '/merchants/:id', to: 'merchants#show'
  get '/merchants/:merchant_id/items/new', to: 'items#new'
  post '/merchants/:merchant_id/items', to: 'items#create'
  get '/merchants/:merchant_id/items', to: 'items#index'
  get '/items', to: 'items#index'
  get '/items/:id', to: 'items#show'
  get '/items/:id/edit', to: 'items#edit'
  patch '/items/:id', to: 'items#update'
  post '/merchants', to: 'merchants#create'
  delete '/merchants/:id', to: 'merchants#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :merchant
  validates_presence_of :name, :description, :price, :image, :active, :inventory, :merchant_id

  def merchant_name
    id = Merchant.find(merchant_id)
    id.name
  end
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates_presence_of :name, :address, :city, :state, :zip
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if params[:merchant_id] == nil
      @items = Item.all
    else
      @merchant = Merchant.find(params[:merchant_id])
      @items = @merchant.items
    end
  end

  def new
    @merchant_id = params[:merchant_id]
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update!(item_params)
    redirect_to "/items/#{@item.id}"
  end

  def create
    @merchant = Merchant.find(params[:merchant_id])
    @item = @merchant.items.create!(item_params)
    redirect_to "/merchants/#{@merchant.id}/items"
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.permit(:name, :description, :price, :image, :inventory)
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def new
  end

  def items
    @merchant = Merchant.find(params[:id])
  end

  def create
    @merchant = Merchant.create(merchant_params)
    redirect_to '/merchants'
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:id])
    @merchant.update(merchant_params)
    redirect_to "/merchants/#{@merchant.id}"
  end

  def destroy
    @merchant = Merchant.find(params[:id])
    @merchant.destroy
    redirect_to '/merchants'
  end

  private

  def merchant_params
    params.permit(:name, :address, :city, :state, :zip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<%= form_tag "/items/#{@item.id}", method: :patch do %>

  <p>Name <%= label_tag :name %></p>
  <%= text_field_tag :name %>

  <p>Price <%= label_tag :price %></p>
  <%= text_field_tag :price %>

  <p>Description <%= label_tag :description %></p>
  <%= text_field_tag :description %>

  <p>Image <%= label_tag :image %></p>
  <%= text_field_tag :image %>

  <p>Inventory <%= label_tag :inventory %></p>
  <%= text_field_tag :inventory %>

  <%= submit_tag "Update Item" %>
  
<% end %>

app/views/items/index.html.erb
<% if @merchant != nil %>
  <%= link_to "Add New Item", "/merchants/#{@merchant.id}/items/new" %>
  <% @merchant.items.each do |item| %>
    <img src="<%= item.image %>" width="200px"></img>
    <p>Name: <%= link_to item.name, "/items/#{item.id}" %></p>
    <p>Price: <%= item.price %></p>
    <p>Status: <%= item.active %></p>
    <p>Quantity: <%= item.inventory %></p>
  <% end %>
<% else %>
  <% @items.each do |item| %>
    <img src="<%= item.image %>" width="200px"></img>
    <p>Name: <%= link_to item.name, "/items/#{item.id}" %></p>
    <p>Description: <%= item.description %></p>
    <p>Price: <%= item.price %></p>
    <p>Status: <%= item.active %></p>
    <p>Quantity: <%= item.inventory %></p>
    <p>Merchant Name: <%= link_to item.merchant_name, "/merchants/#{item.merchant_id}" %></p>
    <% end %>
<% end %>

app/views/items/new.html.erb
<%= form_tag "/merchants/#{@merchant_id}/items", method: :post do %>

  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= label_tag :price %>
  <%= text_field_tag :price %>

  <%= label_tag :description %>
  <%= text_field_tag :description %>

  <%= label_tag :image %>
  <%= text_field_tag :image %>

  <%= label_tag :inventory %>
  <%= text_field_tag :inventory %>

  <%= submit_tag "Add Item" %>

<% end %>

app/views/items/show.html.erb
<img src="<%= @item.image %>" width="200px"></img>
<h3><%= link_to @item.name, "/items/#{@item.id}" %></h3>
<p>Description: <%= @item.description %></p>
<p>Price: <%= @item.price %></p>
<p>Active: <%= @item.active %></p>
<p>Inventory Count: <%= @item.inventory %></p>
<p>Merchant: <%= link_to @item.merchant_name, "/merchants/#{@item.merchant_id}" %></p>
<%= link_to "Edit Item", "/items/#{@item.id}/edit" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to "Items", items_path %>
    <%= link_to "Merchants", merchants_path %>
    <%= yield %>
  </body>
</html>

app/views/merchants/edit.html.erb
<%= form_tag "/merchants/#{@merchant.id}", method: :patch do %>

  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= label_tag :address %>
  <%= text_field_tag :address %>

  <%= label_tag :city %>
  <%= text_field_tag :city %>

  <%= label_tag :state %>
  <%= text_field_tag :state %>

  <%= label_tag :zip %>
  <%= text_field_tag :zip %>

  <%= submit_tag "Update Merchant" %>

<% end %>

app/views/merchants/index.html.erb
<h1>Merchants</h1>

<% @merchants.each do |merchant| %>
<div style="background-color:teal;color:white;padding:20px;">
  <%= link_to merchant.name, "/merchants/#{merchant.id}" %>
  <%= merchant.address %>
  <%= merchant.city %>
  <%= merchant.state %>
  <%= merchant.zip %></div>
<% end %>

<%= link_to "Add Merchant", "merchants/new", method: :get %>

app/views/merchants/new.html.erb
<%= form_tag '/merchants' do %>

  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= label_tag :address %>
  <%= text_field_tag :address %>

  <%= label_tag :city %>
  <%= text_field_tag :city %>

  <%= label_tag :state %>
  <%= text_field_tag :state %>

  <%= label_tag :zip %>
  <%= text_field_tag :zip %>

  <%= submit_tag value = "Submit" %>

<% end %>

app/views/merchants/show.html.erb
<h3><%= link_to @merchant.name, "/merchants/#{@merchant.id}" %></h3>
<p>Street Address: <%= @merchant.address %></p>
<p>City: <%= @merchant.city %></p>
<p>State: <%= @merchant.state %></p>
<p>Zip: <%= @merchant.zip %></p>

<%= link_to "Edit", "/merchants/#{@merchant.id}/edit" %>
<%= link_to "Delete", "/merchants/#{@merchant.id}", method: :delete %>